matrix:
  - name: Markdown
    apsell:
      ignore-case: true
      lang: en
    dictionary:
      wordlists:
        - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "*.mdx"
      - "*.md"
    default_encoding: utf-8
