name: Broken Links Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  broken-links-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install Mintlify
        run: npm i -g mintlify

      - name: Run Broken Links Check
        run: mintlify check-links
